### ISSUE TITLE
Signal SIGUSR2 not available on Windows

### ISSUE THREAD

**Issue by Tezar** [stackimpact/stackimpact-python#5]
For development we use some boxes with Windows. Currently trying to include start agent on Windows produces self-explaining error  

`  File "...\stackimpact\agent.py", line 113, in start
    register_signal(signal.SIGUSR2, _signal_handler)
AttributeError: module 'signal' has no attribute 'SIGUSR2'`

Is it safe to disable this signaling for Win? Unfortunately I am not sure for what is actually SIGUSR2 used in stackimpact so not providing PR.

**Comment by dmelikyan** [comment]
The OS check was missing in the allocation profiler. I've just pushed a fix for it. Please get the latest agent.

FYI, SIGUSR2 is transparently used as a way to initiate allocation profiler on the main thread from timer threads.

**Comment by Tezar** [comment]
Hi,
thanksfor fast fix. Unfortunately it's still failing with same error. Problem occurs immediately when starting agent.
Tried version 1.1.3 ca08a038a5a28a39b1828f6395877253e6d75dd3

**Comment by dmelikyan** [comment]
That's right, a few more things were actually necessary. Please try the latest. Thanks.
